const {Filter} = require("profanity-check")
var fs = require("fs")
const defaultFilter = new Filter()

function profanityCheck(jsonArray) {
    let newArray = [];
    jsonArray.forEach(element => {
        let isProfane = false;
        for (let i = 0; i < jsonArray.length; i++) {
            if(defaultFilter.isProfane(element) === true) {
                console.log(i, defaultFilter.isProfane(element))
            }
            if (defaultFilter.isProfane(element)) {
                isProfane = true;
                break;
            }
        }
        if (!isProfane) {
            newArray.push(element);
        }
    });
    return newArray;
}
const newarrayuwu = profanityCheck([
        "What would you do if you had only 24 hours to live?",
        "What would you do if you found out you could stop time?",
        "What would you do if you were rich?",
        "What would you do if you were the ruler of a country for a day?",
        "What would you do if you were swimming and lost your bathing suit?",
        "What would you do if you were suddenly poor and homeless?",
        "What would you do if you found a bag containing a large amount of cash?",
        "What would you do with the extra time if you had 25-hour days (while everyone else continued to have 24-hour days)?",
        "What would you do if you won a lottery?",
        "What would you do if you were kidnapped?",
        "What would you do if your cell phone fell in the toilet?",
        "What would you do if you went to a public restroom and discovered that there was no paper?",
        "What would you do if you were walking in the forest and saw a wolf?",
        "What would you do if you found out the world was ending?",
        "What would you do if money didn’t matter?",
        "What would you do if you woke up in the morning and found out you were six years old again?",
        "What would you do if you were all of a sudden invisible?",
        "What would you do if you were at home alone at night and heard someone in your house?",
        "What would you do if you saw someone in public with toilet paper stuck to their shoe?",
        "What would you do if you knew that you would go blind in two months?",
        "What would you do if you had two weeks free to do anything you wanted?",
        "What would you do if you found out you had a brother or sister you had never met?",
        "What would you do if you found out your boss was embezzling company funds?",
        "What would you do if you were given the chance to go into outer space?",
        "What would you do if you were told you could never leave your house?",
        "What would you do if you had the opportunity to have any wish granted?",
        "What would you do if you found out someone from your past was planning to kill you?",
        "What would you do if you could see into the future?",
        "What would you do if you began to have uncontrollable bouts of crying or anger?",
        "What would you do if you found out you could talk to animals?",
        "What would you do if you had to choose between wealth and fame?",
        "If time machines existed, what would be the first thing you would do?",
        "If you could have any superpower, what would it be and why?",
        "If you could only eat one food for the rest of your life, what food would it be?",
        "If you could only view one website for the rest of your life, what would it be?",
        "If you were a character in any book, who would it be and why?",
        "If you were a fruit, what fruit would you be and why?",
        "If you were an animal, which animal would you be?",
        "If your house had a theme song, what would it be?",
        "If it turned out that your entire life was is only a dream, would you want to know?",
        "If you had to live with it always being nighttime or daytime, which would you choose and why?",
        "If you had to choose, would you rather give up your sight or your hearing?",
        "If Jurassic Park was a real place, would you want to visit?",
        "If only one book existed, which book would you like it to be?",
        "If you could be another person for a day, who would you choose to be?",
        "If you could hear what someone is thinking for a day, which person’s thoughts would you want to hear?",
        "If you could meet any famous person, dead or alive, who would it be and why?",
        "If you had to disappear, how would you do so and where would you go?",
        "If you could do any job, what would you like to do?",
        "If you could only listen to one song for the rest of your life, which song would you choose?",
        "If you had a time machine, what time period would you like to visit and why?",
        "If you could be granted one wish, what would it be?",
        "If you had to live your life experiencing only one season, would you choose – spring, summer, fall, or winter?",
        "If you had to be stuck living in a TV show for a month, what show would you pick and why?",
        "If you could read minds, would you want to and how would you use the ability?",
        "If you were really a robot, would you want to know?",
        "If someone with multiple personalities tried to kill himself, would it be attempted murder or attempted suicide?",
        "If the police break down your door, do they have to pay for the damage?",
        "If you were a zombie, what famous person’s body would you want to take over?",
        "Is it possible to cry underwater?",
        "Why does a round pizza come in a square box, and then is cut into triangles?",
        "Would you rather forget who everyone else is or who you are?",
        "If you were a child’s toy, what toy would you be and why?",
        "If you were abducted by aliens, would you tell anybody?",
        "If you could live forever on earth as it is now, would you?",
        "When you have questions about your life, have you ever consulted a palm reader or fortune teller?",
        "If you were not you, who would you want to be?",
        "If you could start any business, what business would start, what would it do, and what would it be called?",
        "If you could put wings on any wingless animal, which one would you choose?",
        "If all of a sudden, all animals could talk, would you still eat meat?",
        "If you were given the opportunity to live as long as you want, how long would you want to live?",
        "What would you say to scare someone who did not know you?",
        "How would you like to die and how old do you want to be when you die?",
        "If you were arrested, who would you call with your one telephone call?",
        "If you were given a chance to go into space, would you go?",
        "If you were a color, what color would you choose to be and why?",
        "What do people do that makes you really annoyed when you are with them?",
        "What illegal thing would you like to make legal?",
        "Would you like to become the opposite sex?",
        "You are on vacation and everything is stolen including all cash, credit cards, and identification. What would you do?",
        "You bump another car in a parking lot. Nobody sees you, but the damage is minimal; in fact, it is almost unnoticeable. Would you leave your name and address?",
        "You are in a bank and two people enter and start a hold up. How do you think you would react?",
        "You are stranded on a small island. Do you think you could survive and how would you do so?",
        "You are offered the opportunity to know exactly what you would be doing in 20 years from now, however, you cannot change your future at all. Would you want to know?",
        "You are offered the opportunity to visit any point in history. When would you want to visit and why?",
        "If you were offered the opportunity to stay there, would you?",
        "You will be banished to a desert island and can bring only three things. What will you bring and why?",
        "You are offered a job that pays $2,000 a week. You must sit in a dark room, all alone, in total silence, and remove unknown items from a box and place them on a conveyer belt. Would you take the job?",
        "You are offered the choice of taking a vacation anywhere in the world for any length of time or moving anywhere you wish. Which choice would you make and where would you go?",
        "You are offered $50,000 to go without bathing, brushing your teeth, or using any cosmetic or cleansing products. You cannot tell people why you are doing so. Will you accept the offer or pass?",
        "You can have a free chip put in your brain so that you would know all basic knowledge, such as multiplication tables, history facts, and automatically be able to speak and understand other languages. Would you do so?",
        "You win a contest in which you can choose to have free, unlimited services of a cook, a chauffeur, or a housecleaner. Which one would you choose and why?",
        "You can have any type of pet you want, with no limit on size or expense. What type of animal would you choose and why?",
        "You are informed that your house and all your possessions will be destroyed by an upcoming storm. Which three items (not people or pets) will you choose to save?",
        "If you were a transformer, what vehicle would you turn into?",
        "What laws would you abolish/create if you could?",
        "If extra lives were a thing in the real world, how would you get them?",
        "If you were a food, what food would you be?",
        "What animal would be way better if it was covered in scales?",
        "If you could design a planet, what would your perfect planet look like?",
        "What would be your strategy for a zombie apocalypse?",
        "If you could be the CEO of any company, what company would you choose?",
        "What two animals would you like to switch the sounds they make?",
        "Would you want to permanently feel zero pain if given the chance?",
        "What cartoon world do you wish you could live in for a week?",
        "What do you wish grew on trees?",
        "What weird thing would you make socially acceptable if you could?",
        "If every time you snapped your fingers, you would instantly be transported to a random point in humanity’s timeline, would you snap your fingers?",
        "If you were perpetually surrounded by one aroma (besides your natural smell) which you and everyone around you could smell, what would it be?",
        "If you could level up any aspect of yourself (i.e., strength, intelligence, charisma, etc.) but you had to decrease another aspect of yourself by the same amount, what aspects would you increase, and which would you decrease?",
        "If humans lost the ability to see all color except one, which color would you want to survive?",
        "If you were a dictator of a small country, what crazy dictator things would you do?",
        "If your sheets had to be made of deli meats, what meat would want them made of?",
        "If you could put wings on any species of animal, what animal would you choose?",
        "How would the world be different if zeppelins had caught on and were the dominant form of air travel?",
        "Every day 12 things appear in your backyard, they are random, but all start with a letter of your choosing. What letter do you choose?",
        "If money wasn’t a concern where would you live, what would you do, and what would your lifestyle look like?",
        "If when you died, you could cease to exist or wander the earth forever never being able to interact with anything, which would you choose?",
        "If you could move anywhere and still have a livable wage, where would you like to move?",
        "If you could get a ticket to any show or event, what would you want a ticket to?",
        "If you could go back in time and give your parents advice before you were born, what advice would you give them?",
        "If everyone was mentally incapable of lying, how would that change the world?",
        "If you could be invisible, but it would mean being permanently invisible, would you want to be?",
        "If you had to do a dance that had never been done in the history of mankind or be killed, what kind of dance would you do?",
        "If you could erase one thing from existence, even the memory of the thing, what would it be?",
        "If you were required by law to get a full body tattoo, what would you get tattooed over your entire body?",
        "If you were head of product development at a major fast food chain, what food abomination would you create?",
        "If you could change the sounds your body makes (i.e., burp, fart, yawn, sneeze, etc.), what new sound effects would replace the normal sounds of your body?",
        "If you were forced into gladiatorial combat, but could only choose a weapon that isn’t typically considered a weapon, what non-conventional weapon would you choose?",
        "If you could replace any word in common usage with another word and no one would know, which word would you choose?",
        "If you could go back and hands down win any argument you’ve had with anyone, what argument would you choose to win?",
        "If you were reincarnated as an animal based on your personality, what animal do you think you would come back as?",
        "If you had to be haunted by a ghost for the rest of your life but could choose which dead person the ghost would be, who would you choose as your ghost?",
        "If people were required to post the bad as well as the good stuff that happened to them on social media, would social media platforms be more or less popular than they are now?",
        "If you worked in the entertainment industry and had a pseudonym, what would your alias be?",
        "What futuristic thing from a sci-fi movie or book do you really wish existed right now?",
        "If you had an animal or plant renamed in your honor, what would you want to carry your name?",
        "If you could create any one reality TV show, and it was guaranteed to air, what show would you want to put on TV?",
        "If you had to get a tail, what tail would you want and what would you use it for?",
        "If you were a superhero/villain, but could only have superpowers that weren’t already taken, what new powers would you choose and what would your name be?",
        "If you could be a top tier professional athlete in any sport, what sport would you play and why?",
        "If you were given the rather lame superpower of being able to make any food you touch go bad, what would you do with that power?",
        "You can transport one furious elephant into any point in history, where would you put it?",
        "If someone offered you $10,000 every time they punched you in the face, how many times would you want to be hit?",
        "If someone left you a cottage somewhere in the countryside in their will, where would you want the cottage to be located?",
        "Would you want to live in a world where everyone’s thoughts appeared as text above their head?",
        "If you could start a secret society, what would be its goals and who would you include?",
        "If you could only eat the same breakfast, the same lunch (different than breakfast), and the same dinner (different than lunch) every day, what three meals would you choose?",
        "What two-hour chunk of history would you want a video of if you could have video of any point in history?",
        "If you could choose any job to be replaced by robots, what job would you make obsolete?",
        "Would you choose to become more intelligent if it meant you were generally unhappier?",
        "If you were obscenely wealthy, what weird eccentricities would you indulge in?",
        "If your dog or cat suddenly spoke one sentence and then never spoke again, what would be the most unsettling sentence they could say?",
        "How would the world change if there was no internal monologue and everything you thought, you spoke out loud?",
        "What movie worthy heist would you pull if you knew, in the end, you would get away with it?",
        "If you could snap your fingers and make any one species go extinct, which species would you choose?",
        "Would you want a house where every wall was made of giant TVs if you could choose the channels but never turn them off?",
        "If you started an activist group, what would it fight for and what would it be called?",
        "How would our view of space change if the moon was actually made of cheese?",
        "Would you rather be incredibly witty and outgoing or quiet and incredibly intelligent or just stay the way you are now?",
        "What would be the first few things you would try if you found out you were completely impervious to physical harm?",
        "If you could choose a nickname and have people call you it with complete seriousness no matter how ridiculous, what nickname would you want?",
        "How would you change how you acted if you knew 100% that the world was a simulation?",
        "If you were given any one luxury item, but you couldn’t sell it, what luxury item would you want?",
        "If you could live in anyone’s head for fifteen minutes (Being John Malkovich style), who would you choose?",
        "If given a chance, would you drink milk from animals we usually don’t drink milk from? (i.e., bat milk, cheetah milk, monkey milk, etc.)",
        "If you were the next pied piper, what animal would you want to be able to compel to follow you?",
        "If someone created a bar or cafe with just your tastes in mind, what would it look like?",
        "If you were offered $50,000 to dance for 2 minutes with no music in front of a stadium full of people, would you do it?",
        "What type of dancing would you do?",
        "What would you do if you had your own intergalactic space ship roughly the size of a house?",
        "If you could choose one element to control, what element would you choose?",
        "Would you take a weekend job for 20k a year to be a human scarecrow and chase birds from fields?",
        "If you were a fashion icon and whatever you wore would become a fashion trend, what fashion trends would you start?",
        "If you could body swap with any person for 24 hours, who would you choose?",
        "What shape would you want your house to be if it could be any shape and still function?",
        "If you could ask three questions to anyone in history, who would you choose and what questions would you ask? Assuming they would understand your questions and you would understand their answers.",
        "If you could put just one word into any document in history, what word would you choose and where would you put it?",
        "What would be the most interesting or exciting thing to make a floor in a house out of?",
        "If you were tasked with redesigning your country’s flag, how would you change it?",
        "If you were chosen to be the first human to make contact with aliens, would you want to?",
        "If you died and had to choose one place to haunt for the rest of eternity, where would you choose to haunt?",
        "You get one text, no more than 160 characters, that gets sent to everyone’s phone. What does it say?",
        "Would you sign up to be a colonist on another planet if it meant you would never be able to return to earth?",
        "If you were a 90’s cartoon evil villain, where would your base be and what would it look like / have inside?",
        "What would your henchmen / henchwomen wear as uniforms?",
        "If you were the king of an ancient civilization what would you want your tomb to look like?",
        "If you could call yourself when you were fifteen years old for a twenty-minute conversation, what would you tell yourself?",
        "If you could choose what the next crazy fake health trend was, what health trend would you create?",
        "Everyone always thinks they’d be royalty or a knight if they were born in Medieval times, but let’s be honest, you probably wouldn’t be. So, what kind of peasant do you think you’d be if you were born in medieval times?",
        "If your life was made into a movie which actor would play you?",
        "What kind of movie or TV show would you make if money / skill wasn’t an object?",
        "What amusement park do you wish existed?",
        "What cute cartoon character would be absolutely terrifying if it existed in the real world?",
        "What animal would be the cutest if it was the size of a chihuahua?",
        "If you could implant one false memory in the minds of everyone in your country, what would that memory be?",
        "If you were on death row but could choose any way to be executed as long as you died within a couple of days, how would you want to die?",
        "What sport would you like to compete in professionally if you had the ability and skill to?",
        "What would be great and what would be terrible about all humans having translucent skin and muscles so that you could see all the organs working?",
        "If you had a symbol or crest that represented you, what would it look like?",
        "If you had to suffer through a massive natural disaster but could choose which disaster to face, which would you choose?",
        "Would you choose to know your future if it meant forgetting your past?",
        "If you had to join the circus, what type of performer would you be?",
        "If you could live under any form of government, what type of government would you choose (Don’t go with this one if you have or one of your friends have strong political opinions) ?",
        "What kind of business would you like to start if you were given a chance?",
        "If you could control your dreams, what would you dream about?",
        "What would you do if a teaspoon of your tears could be used to cure cancer in one person?",
        "Your superpower is that you can give phobias to people, what fun and interesting things would you make people afraid of?",
        "If you could tack on 100 years to the end of your life, but you would be old and frail during those 100 years, would you still do it?",
        "If you could deck out one room in your house in any way you’d like, which room would you choose and what would you do to it?",
        "If aliens took over and humans were put into zoos, what would you want in your zoo enclosure?",
        "If you could travel anywhere in the world, where would you visit and why?",
        "If you could merge two games together and make a new one, what games would you choose and what would be the result?",
        "If hide and seek were a major sport in the Olympics, what would it be like?",
        "If you could change what people say after someone sneezes, what would be the funniest thing for people to say?",
        "What would be the cutest non-conventional military unit that would still function as an effective fighting unit?",
        "If your hands were frozen in one position or gesture, what position would want them stuck in?",
        "If you could accomplish simple tasks while sleeping and still get a good night’s sleep, what would you want your body to do while you were sleeping?",
        "If Jedi were real, but you had to give up all your possessions and never have a romantic relationship, would you still become a Jedi?",
        "What would you do if you were suddenly given world-class hacking knowledge and ability?",
        "If you could speak two other languages fluently, what languages would you want to speak?",
        "If you won the lottery, what would NOT change?",
        "If you could bring back any canceled TV series, which TV show would you choose to bring back?",
        "If you had to prove you were human and not an AI in 5 minutes via a text conversation, how would you do it?",
        "If you could go back and uninvent something, what invention would you erase from history?",
        "If you could know the truth behind any one secret or mystery, what would it be?",
        "If you could rename any five animals, what would you rename and what would their new names be?",
        "If you had an endless supply of LEGOs but couldn’t sell them, what would you build?",
        "If your salary was doubled, what would you do with the extra income?",
        "If you found out you were going to die in a week, what would you do with your remaining time?",
        "If all animals became as intelligent as humans and were miraculously able to speak, what jobs would be well suited to which animals?",
        "If you could make one thing taste like another, what would it be?",
        "If you could choose any mode of transportation, no matter how ridiculous, what method of transportation would you want to use to get around town?",
        "Assuming you don’t get seasick, what would your dream sailboat or boat look like and what would you name it?",
        "If you were tasked with making school more fun, but it still had to be effective at teaching students, what would you change?",
        "If you could make a medicine that would cure one thing, and that thing could be anything, what would your miracle medicine cure be?",
        "If you could be born again in any country, as any race, and as any gender, what would you choose?",
        "What fantasy creature would you love to bring into the real world?",
        "If you could afford a live-in butler or maid, would you want one?",
        "What sound do you think you would miss most if you went deaf?",
        "What animal would you create if you could design and bring into the world, one new creature?",
        "If you could know when and how someone would die just by shaking their hands but couldn’t change their fate, how would you use that power?",
        "If you could harmoniously unite two countries into one, what two countries would you choose?",
        "If you could go back and undo one thing you did, what would you undo?",
        "If you were able to throw a party and money wasn’t an issue, what kind of party would you throw?",
        "If you could make any non-edible thing edible to humans, what would you choose?",
        "When would you be born if you could choose to be born at another time?",
        "If androids were a thing, how do you think people would treat them?",
        "If you had a handful of modeling clay and whatever you made would become real until you willed it back into clay, what would you use it for / make?",
        "If you could control one aspect of your body that usually is autoregulated (i.e., body temperature, digestion, heart rate, etc.), what system would you control?",
        "If you were a professional wrestler in the WWE, what would your name and identity be?",
        "What would you do with a real bag of holding?",
        "If you put out a brand of beer, wine, soda, or another beverage, what would it be, what would you call it, and how would you differentiate your brand?",
        "If you could get every country and every person in the world to work on one project or goal, what would it be?",
        "If you could design a new holiday, what holiday would you create and what traditions would it have?",
        "If you could be fluent in four languages, which languages would you choose?",
        "If you could know the internet history of any one individual, who would it be?",
        "If you could redesign the human species, what parts would you add on or take out?",
        "If you could become three times bigger or fifty times smaller at will, which do you think you would spend more time as, big you or small you? Why?",
        "If you could choose any vehicle to drive around for a couple of hours, which vehicle would you choose?",
        "If you had a pen with magical ink inside, what would happen when you wrote something?",
        "You can choose anyone in the world to become friends with, who would you choose?",
        "If you could be an NPC in any videogame, what game would you choose to reside in?",
        "How would the world change if mammals (including humans) laid eggs instead of giving birth?",
        "What would you do if you could change/introduce one law?",
        "What would you do if you would never have to sleep again?",
        "What would you do if you could only eat one food for the rest of your life?",
        "What would you do if you could transform yourself into any animal?",
        "What would you do if you could be invisible to the human eye?",
        "What would you do if you found nudes of yourself online right now?",
        "What would you do if you could change one event in history?",
        "What would you do if you didn’t have to work for a living?",
        "What would you do if you knew you were going to die tomorrow?",
        "What would you do if you meet an alien?",
        "What would you do if you were stuck with a pregnant woman in an elevator, and she went into labor?",
        "What would you do if a kid starts kicking your ass and its mother doesn’t intervene?",
        "What would you do if you got caught masturbating by your flatmate?",
        "What would you do if all drugs were legal?",
        "What would you do if you could control your dreams?",
        "What would you do if you were left on an isolated island?",
        "What would you do if you found 1000 dollars on the street?",
        "What would you do if you didn’t have any anxiety?",
        "What would you do if you were god?",
        "What would you do if you were immortal?",
        "What would you do if you could switch gender for a day?",
        "What would you do if you fell into a gorilla’s enclosure?",
        "What would you do if your mother turned into a zombie right in front of your eyes?",
        "What would you do if you had the chance to have sex with Ryan Gosling?",
        "What would you do if you were given three wishes? What would you wish for?",
        "What would you do if reincarnation was real, and you could choose what animal you become in your next life?",
        "What would you do if you had the opportunity to time travel once?",
        "What would you do if you had the chance to end all war by killing 10 innocent children?",
        "What would you do if you had to choose between winning the lottery or live twice as long?",
        "What would you do if you had the chance to fly to space?",
        "What would you say if the whole world were listening?",
        "What would you do if your best friend told you he/she killed someone?",
        "What would you do if you saw someone steal something from the grocery store?",
        "What would you do if you could do anything illegal without getting arrested?",
        "What would you do if someone tries to rob you while you’re at home sleeping?",
        "What would you do if your friend has a terrible breath? Would you tell them?",
        "What would you do if you caught your parents having sex?",
        "What would you do if you’re on a train and a person who smells horrible sits next to you?",
        "What would you do if you saw a person crying on a park bench?",
        "What would you do if you figured out the password to your partner’s phone right now?",
        "What would you do if you could hypnotize anyone just by looking at them?",
        "What would you do if you found out you were pregnant at this moment?",
        "What would you do if you’re at a hair salon and got a really bad hair cut? What would you tell the hairdresser?",
        "What would you do if you and your 16-year-old self could have a sleepover?",
        "What would you do if someone cheats on you?",
        "What would you do if I break your heart?",
        "What would you do if I never said “yes” to your proposal?",
        "What would you do if we were stuck in a box in this position?",
        "What would you do if I lie to you about something vital?",
        "What would you do if I tear your certificates just because I am upset?",
        "What would you do if the world was ending?",
        "What would you do if there was a dragon stuck under your bed?",
        "What would you do if I tell you that I never loved you?",
        "What would you do if a celebrity gives you a shoutout on Instagram without you asking for it?",
        "What would you do if you and I were the only people on Earth?",
        "What would you do if someone is crushing on you, and you like him or her as well?",
        "What would you do if I kissed you?",
        "What would you do if a celebrity kissed you without your consent?",
        "What would you do if you were the ugliest thing on Earth?",
        "What would you do if there were no weekends?",
        "What would you do if love is something you buy from the market?",
        "What would you do if you fall for someone?",
        "What would you do if your son was all alone crying at home?",
        "what would you do if a child was afraid of a character?",
        "What would you do if you found out that you don’t have a penis/vagina?",
        "What would you do if you woke up and the house is on fire?",
        "What would you do if you find out that you are not the father/mother of your kids?",
        "What would you do if you have the power to go to the future and the past?",
        "What would you do if you have to sacrifice someone you love to live or you die?",
        "What would you do if your worst enemy becomes the boss in your place of work?",
        "What would you do if there’s no reason to live?",
        "What would you do if everyday emotions were confusing or challenging?",
        "What would you do if you were thrown out of school?",
        "What would you do if your class teacher catches you doing something crazy?",
        "What would you do if life is something you pay for?",
        "What would you do if your friends and families no longer trust you?",
        "What would you do if one of your classmates feel jealous of you?",
        "What would you do if there’s something like life after death?",
        "What would you do if you have superpowers?",
        "What would you do if you have the gadgets to control the whole world?",
        "What would you do if the recent technology crashes and we all go back to the early 40s?",
        "What would you do if you lose all you have worked for in life overnight?",
        "What would you do if you had all the time and money in the world?",
        "What would you do if police try to arrest me for no reason?",
        "What would you do if you wake up and realize that you cannot move your body anymore?",
        "What would you do if your friend steals from you?",
        "What would you do if someone just gave you $1 million?",
        "What would you do if a stranger kicks your balls and run away?",
        "What will you do if govt allows people to commit crimes and go free?",
        "What would you do if you won a lottery?",
        "What would you do someone finds out your biggest secret?",
        "What would you do if all the electricity in the world just stopped?",
        "What would you do if you were offered everything in life for free, but you have to live alone without the internet?",
        "What would you do if you become a celebrity?",
        "What would you do if you had five years to live?",
        "What would you do if you weren’t afraid?",
        "What would you do if you wake up and see yourself in wonderland?",
        "What would you do if money didn’t matter?",
        "what would you do if you were invisible?",
        "What would you do if you were the president?",
        "What would you do if you can make dreams reality?",
        "What would you do if everyone was happy?",
        "What would you if you were a god?",
        "What would you do if everyone disappeared to thin air?",
        "What would you do if you have an adult’s abilities?",
        "What would you do if no one was watching you?",
        "What would you do if you were given superpowers?",
        "What would you do if you could see into the future?",
        "What would you do if you found out someone from your past was planning to kill you?",
        "What would you do if you had the opportunity to have any wish granted?",
        "What would you do if you were told you could never leave your house?",
        "What would you do if you were given the chance to go into outer space?",
        "What would you do if you found out your boss was embezzling company funds?",
        "What would you do if you found out you had a brother or sister you had never met?",
        "What would you do if you had two weeks free to do anything you wanted?",
        "What would you do if you knew that you would go blind in two months?",
        "What would you do if you had to choose between wealth and fame?",
        "What would you do if you found out you could talk to animals?",
        "What would you do if you began to have uncontrollable bouts of crying or anger?",
        "What would you do if you had only 24 hours to live?",
        "What would you do if you were rich?",
        "What would you do if you found out you could stop time?",
        "What would you do if you were swimming and lost your bathing suit?",
        "What would you do if you were the ruler of a country for a day?",
        "What would you do if you found a bag containing a large amount of cash?",
        "What would you do if you were suddenly poor and homeless?",
        "What would you do if you were invisible?",
        "What would you do if your cell phone fell in the toilet?",
        "What would you do if you were kidnapped?",
        "What would you do if you went to a public restroom and discovered that there was no paper?",
        "What would you do if you were given superpowers?",
        "What would you do if no one was watching you?",
        "What would you do if you have an adult’s abilities?",
        "What would you do if everyone disappeared into thin air?",
        "What would you do if everyone was happy?",
        "What would you do if you can make dreams a reality?",
        "What would you do if you were the president?",
        "What would you do if you woke up and saw yourself in wonderland?",
        "What would you do if you weren’t afraid?",
        "What would you do if you had five years to live?",
        "What would you do if you become a celebrity?",
        "What would you do if you were offered everything in life for free, but you have to live alone without the internet?",
        "What would you do if all the electricity in the world just stopped?",
        "What would you do if someone finds out your biggest secret?",
        "What would you do if a stranger kicks your balls and ran away?",
        "What would you do if your friend steals from you?",
        "What would you do if you woke up and realized that you cannot move your body anymore?",
        "What would you do if the police try to arrest me for no reason?",
        "What would you do if I tore your certificates just because I am upset?",
        "What would you do if the recent technology crashes and we all go back to the early 40s?",
        "What would you do if a celebrity gives you a shoutout on Instagram without you asking for it?",
        "What would you do if I told you that I never loved you?",
        "What would you do if there was a dragon stuck under your bed?",
        "What would you do if you found out the world was ending?",
        "What would you do if you were god?",
        "What would you do if you could make your dreams a reality?",
        "What would you do if there’s no reason to live?",
        "What would you do if your worst enemy became the boss in your place of work?",
        "What would you do if you have to sacrifice someone you love to live or you die?",
        "What would you do if you had the power to go to the future and the past?",
        "What would you do if you found out that you are not the father/mother of your kids?",
        "What would you do if you woke up and the house was on fire?",
        "What would you do if you woke up and the house is on fire?",
        "What would you do if love is something you buy from the market?",
        "What would you do if you met an alien?",
        "What would you do if you had the chance to fly to space?",
        "What would you do if you had the chance to end all war by killing 10 innocent children?",
        "What would you do if you had the opportunity to time travel once?",
        "What would you do if reincarnation was real, and you could choose what animal you become in your next life?",
        "What would you do if you were given three wishes?",
        "What would you do if your mother turned into a zombie right in front of your eyes?",
        "What would you do if you fell into a gorilla’s enclosure?",
        "What would you do if you could switch gender for a day?",
        "What would you do if you knew you were going to die tomorrow?",
        "What would you do if you didn’t have to work for a living?",
        "What would you do if you could change one event in history?",
        "What would you do if you found nudes of yourself online right now?",
        "What would you do if you could be invisible to the human eye?",
        "What would you do if you could transform yourself into any animal?",
        "What would you do if you could only eat one food for the rest of your life?",
        "What would you do if you would never have to sleep again?",
        "What would you do if you could change/introduce one law?",
        "What would you do if you were stuck with a pregnant woman in an elevator, and she went into labor?",
        "What would you do if you became a robot?",
        "What would you do if you had to give up your sight or your hearing?",
        "What would you do if you could be granted one wish?",
        "What would you do if Jurassic Park was a real place?",
        "What would you do if you had to choose to be dumb or ugly?",
        "What would you do if you had to live with it always being nighttime or daytime?",
        "What would you do if you could be a character in any book?",
        "What would you do if you could meet any famous person, dead or alive?",
        "What would you do if you had to be stuck in your room for a month?",
        "What would you do if it turned out that your entire life was only a dream?",
        "What would you do if you were immortal?",
        "What would you do if your best friend told you he/she killed someone?",
        "What would you do if you didn’t have any anxiety?",
        "What would you do if you found 1000 dollars on the street?",
        "What would you do if you were left on an isolated island?",
        "What would you do if someone tries to rob you while you’re at home sleeping?",
        "What would you do if you could do anything illegal without getting arrested?",
        "What would you do if you caught your partner cheating on you with your best friend?",
        "What would you do if you saw someone steal something from the grocery store?",
        "What would you do if you could control your dreams?",
        "What would you do if all drugs were legal?",
        "What would you do if you got caught masturbating by your flatmate?",
        "What would you do if a kid starts kicking your ass and its mother doesn’t intervene?",
        "What would you do if you and your 16-year-old self could have a sleepover?",
        "What would you do if you’re at a hair salon and got a really bad haircut?",
        "What would you do if you found out you were pregnant at this moment?",
        "What would you do if you could hypnotize anyone just by looking at them?",
        "What would you do if you figured out the password to your partner’s phone right now?",
        "What would you do if you saw a person crying on a park bench?",
        "What would you do if you’re on a train and a person who smells horrible sits next to you?",
        "What would you do if you could only view one website for the rest of your life?",
        "What would you do if you had a time machine?",
        "What would you do if you could hear what someone was thinking for a day?",
        "What would you do if you could be another person for a day?",
        "If you could only listen to one song for the rest of your life, which song would you choose?",
        "What would you do if you could do any job?",
        "What would you do if you could read minds?",
        "What would you do if you were abducted by aliens?",
        "What would you do if you could live forever on the earth?",
        "What would you do if we changed to each other?",
        "What would you do if you could start any business?",
        "What would you do if you had wings?",
        "What would you do if you were arrested?",
        "What would you do if you were given a change to go into space?",
        "What would you do if you became a girl?",
        "What would you do if everything was stolen including all cash, credit cards, and identification on your vacation?",
        "What would you do if you bumped another car in a parking lot and nobody saw you?",
        "What would you do if you were in a bank and two people entered and started a hold up?",
        "What would you do if were able to know what exactly you would be doing in 20 years from now but you could not change your future at all?",
        "What would you do if you were banished to a desert island?",
        "What would you do if you were offered the choice of taking a vacation anywhere in the world for any length of time you wish?",
        "What would you do if you could have a free chip put in your brain so that you would know all basic knowledge?",
        "What would you do if you could have any type of pet you want, with no limit on size of expense?",
        "What would you do if you could abolish laws and create laws?",
        "What would you do if you could design another planet?",
        "What would you do if you permanently felt zero pain?",
        "What would you do if you could erase one thing from existence?",
        "What would you do if you were given the rather lame superpower of being able to make any food you touch go bad?",
        "What would you do if someone offered you $10,000 every time they punched you in the face?",
        "What would you do if you could start a secret society?",
        "What would you do if you could make any one species go extinct?",
        "What would you do if you could swap body with any person for 24 hours?",
        "What would you do if you were the first human to make contact with aliens?",
        "What would you do if you were the king of an ancient civilization?",
        "What would you do if you could implant one false memory in the minds of everyone in your country?",
        "What would you do if you could change laws?",
        "What would you do if you could put a new word in the dictionary?",
        "What would you do if money didn’t matter?",
        "What would you do if you had all the time and money in the world?",
        "What would you do if you won a lottery?",
        "What would you do if you had to choose between winning the lottery or live twice as long?",
        "What would you do if money wasn’t a concern and you could live anywhere you wish?",
        "What would you do if you could move anywhere and still have a livable wage?",
        "What would you do if someone cheats on you?",
        "What would you do if I break your heart?",
        "What would you do if I never said “yes” to your proposal?",
        "What would you do if I lie to you about something vital?",
        "What would you do if I tell you that I never loved you?",
        "What would you do if you and I were the only people on Earth?",
        "What would you do if I kissed you?",
        "What would you do if you fall for someone?"
    ])
    fs.writeFile('wwyd.json', JSON.stringify(newarrayuwu), err => {
        if (err) {
          console.error(err);
          return;
        }
      });
